# ---- deps ----
FROM node:20-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---- builder ----
FROM node:20-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG APIFY_TOKEN
ARG APIFY_API_BASE_URL
ARG PROSPECT_APIFY_INSTAGRAM_TASK_ID
ARG PROSPECT_APIFY_INSTAGRAM_ACTOR_ID
ARG PROSPECT_APIFY_LINKEDIN_TASK_ID
ARG PROSPECT_APIFY_LINKEDIN_ACTOR_ID
ARG PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID
ARG PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID
ARG GEMINI_API_KEY
ARG GEMINI_API_BASE_URL
ARG GEMINI_MODEL
ARG GOOGLE_MAPS_API_KEY
ARG UAZAPI_API_URL
ARG UAZAPI_INSTANCE_ID
ARG UAZAPI_API_TOKEN
ARG OUTREACH_CRON_SECRET
ARG OUTREACH_DELAY_MS
ARG OUTREACH_MIN_SCORE
ARG OWNER_PHONE
ARG ENABLE_LOCAL_AUTH
ARG LOCAL_AUTH_EMAIL
ARG LOCAL_AUTH_PASSWORD
ARG LOCAL_AUTH_NAME
ARG LEADS_STORAGE_PROVIDER
ARG USE_LOCAL_STORAGE
ARG PROSPECTING_ENABLE_DEMO_FALLBACK

# Expõe ARGs como ENV para o build do Next.js
ENV SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
    SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY \
    NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXTAUTH_URL=$NEXTAUTH_URL \
    NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
    APIFY_TOKEN=$APIFY_TOKEN \
    APIFY_API_BASE_URL=$APIFY_API_BASE_URL \
    PROSPECT_APIFY_INSTAGRAM_TASK_ID=$PROSPECT_APIFY_INSTAGRAM_TASK_ID \
    PROSPECT_APIFY_INSTAGRAM_ACTOR_ID=$PROSPECT_APIFY_INSTAGRAM_ACTOR_ID \
    PROSPECT_APIFY_LINKEDIN_TASK_ID=$PROSPECT_APIFY_LINKEDIN_TASK_ID \
    PROSPECT_APIFY_LINKEDIN_ACTOR_ID=$PROSPECT_APIFY_LINKEDIN_ACTOR_ID \
    PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID=$PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID \
    PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID=$PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID \
    GEMINI_API_KEY=$GEMINI_API_KEY \
    GEMINI_API_BASE_URL=$GEMINI_API_BASE_URL \
    GEMINI_MODEL=$GEMINI_MODEL \
    GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY \
    UAZAPI_API_URL=$UAZAPI_API_URL \
    UAZAPI_INSTANCE_ID=$UAZAPI_INSTANCE_ID \
    UAZAPI_API_TOKEN=$UAZAPI_API_TOKEN \
    OUTREACH_CRON_SECRET=$OUTREACH_CRON_SECRET \
    OUTREACH_DELAY_MS=$OUTREACH_DELAY_MS \
    OUTREACH_MIN_SCORE=$OUTREACH_MIN_SCORE \
    OWNER_PHONE=$OWNER_PHONE \
    ENABLE_LOCAL_AUTH=$ENABLE_LOCAL_AUTH \
    LOCAL_AUTH_EMAIL=$LOCAL_AUTH_EMAIL \
    LOCAL_AUTH_PASSWORD=$LOCAL_AUTH_PASSWORD \
    LOCAL_AUTH_NAME=$LOCAL_AUTH_NAME \
    LEADS_STORAGE_PROVIDER=$LEADS_STORAGE_PROVIDER \
    USE_LOCAL_STORAGE=$USE_LOCAL_STORAGE \
    PROSPECTING_ENABLE_DEMO_FALLBACK=$PROSPECTING_ENABLE_DEMO_FALLBACK

# Grava arquivo .env para copiar ao runner
RUN printenv | grep -E '^(SUPABASE_|NEXT_PUBLIC_|NEXTAUTH_|APIFY_|PROSPECT_|GEMINI_|GOOGLE_|UAZAPI_|OUTREACH_|OWNER_|ENABLE_|LOCAL_AUTH|LEADS_|USE_LOCAL|PROSPECTING_)' > /app/.env.production

RUN npm run build

# ---- runner ----
FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/node_modules/pdfkit/js/data ./node_modules/pdfkit/js/data
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
RUN mkdir -p /app/data

EXPOSE 3000
CMD ["node", "server.js"]
