# ---- deps ----
FROM node:20-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---- builder ----
FROM node:20-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ---- runner ----
FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

# Declara todos os build args do EasyPanel
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG APIFY_TOKEN
ARG APIFY_API_BASE_URL
ARG PROSPECT_APIFY_INSTAGRAM_TASK_ID
ARG PROSPECT_APIFY_INSTAGRAM_ACTOR_ID
ARG PROSPECT_APIFY_LINKEDIN_TASK_ID
ARG PROSPECT_APIFY_LINKEDIN_ACTOR_ID
ARG PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID
ARG PROSPECT_APIFY_GOOGLE_MAPS_ACTOR_ID
ARG PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID
ARG PROSPECT_APIFY_GOOGLE_MY_BUSINESS_ACTOR_ID
ARG GEMINI_API_KEY
ARG GEMINI_API_BASE_URL
ARG GEMINI_MODEL
ARG GOOGLE_MAPS_API_KEY
ARG UAZAPI_API_URL
ARG UAZAPI_INSTANCE_ID
ARG UAZAPI_API_TOKEN
ARG OUTREACH_CRON_SECRET
ARG OUTREACH_DELAY_MS
ARG OUTREACH_MIN_SCORE
ARG OWNER_PHONE
ARG ENABLE_LOCAL_AUTH
ARG LOCAL_AUTH_EMAIL
ARG LOCAL_AUTH_PASSWORD
ARG LOCAL_AUTH_NAME
ARG LEADS_STORAGE_PROVIDER
ARG USE_LOCAL_STORAGE
ARG PROSPECTING_ENABLE_DEMO_FALLBACK
ARG LOG_LEVEL

# Grava .env.production a partir dos build args
RUN printf "" > /app/.env.production && \
    for VAR in \
      SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY \
      NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY \
      NEXTAUTH_URL NEXTAUTH_SECRET \
      APIFY_TOKEN APIFY_API_BASE_URL \
      PROSPECT_APIFY_INSTAGRAM_TASK_ID PROSPECT_APIFY_INSTAGRAM_ACTOR_ID \
      PROSPECT_APIFY_LINKEDIN_TASK_ID PROSPECT_APIFY_LINKEDIN_ACTOR_ID \
      PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID PROSPECT_APIFY_GOOGLE_MAPS_ACTOR_ID \
      PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID PROSPECT_APIFY_GOOGLE_MY_BUSINESS_ACTOR_ID \
      GEMINI_API_KEY GEMINI_API_BASE_URL GEMINI_MODEL \
      GOOGLE_MAPS_API_KEY \
      UAZAPI_API_URL UAZAPI_INSTANCE_ID UAZAPI_API_TOKEN \
      OUTREACH_CRON_SECRET OUTREACH_DELAY_MS OUTREACH_MIN_SCORE \
      OWNER_PHONE \
      ENABLE_LOCAL_AUTH LOCAL_AUTH_EMAIL LOCAL_AUTH_PASSWORD LOCAL_AUTH_NAME \
      LEADS_STORAGE_PROVIDER USE_LOCAL_STORAGE PROSPECTING_ENABLE_DEMO_FALLBACK \
      LOG_LEVEL; do \
      eval "VAL=\$$VAR"; \
      if [ -n "$VAL" ]; then echo "${VAR}=${VAL}" >> /app/.env.production; fi; \
    done

# Arquivos pdfkit necessários em runtime
COPY --from=builder /app/node_modules/pdfkit/js/data ./node_modules/pdfkit/js/data

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
COPY --from=builder /app/start.sh ./start.sh

# Pasta de dados persistentes
RUN mkdir -p /app/data && chmod +x /app/start.sh

EXPOSE 3000
CMD ["/bin/sh", "/app/start.sh"]
