# ---- deps ----
FROM node:20-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---- builder ----
FROM node:20-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Variáveis de ambiente passadas pelo EasyPanel como build args
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG UAZAPI_API_URL
ARG UAZAPI_INSTANCE_ID
ARG UAZAPI_API_TOKEN
ARG OUTREACH_CRON_SECRET
ARG OWNER_PHONE
ARG GEMINI_API_KEY
ARG ENABLE_LOCAL_AUTH
ARG LOCAL_AUTH_EMAIL
ARG LOCAL_AUTH_PASSWORD
ARG OUTREACH_DELAY_MS

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV UAZAPI_API_URL=$UAZAPI_API_URL
ENV UAZAPI_INSTANCE_ID=$UAZAPI_INSTANCE_ID
ENV UAZAPI_API_TOKEN=$UAZAPI_API_TOKEN
ENV OUTREACH_CRON_SECRET=$OUTREACH_CRON_SECRET
ENV OWNER_PHONE=$OWNER_PHONE
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV ENABLE_LOCAL_AUTH=$ENABLE_LOCAL_AUTH
ENV LOCAL_AUTH_EMAIL=$LOCAL_AUTH_EMAIL
ENV LOCAL_AUTH_PASSWORD=$LOCAL_AUTH_PASSWORD
ENV OUTREACH_DELAY_MS=$OUTREACH_DELAY_MS
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ---- runner ----
FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

# Copiar variáveis para o runtime
ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG UAZAPI_API_URL
ARG UAZAPI_INSTANCE_ID
ARG UAZAPI_API_TOKEN
ARG OUTREACH_CRON_SECRET
ARG OWNER_PHONE
ARG GEMINI_API_KEY
ARG ENABLE_LOCAL_AUTH
ARG LOCAL_AUTH_EMAIL
ARG LOCAL_AUTH_PASSWORD
ARG OUTREACH_DELAY_MS

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV UAZAPI_API_URL=$UAZAPI_API_URL
ENV UAZAPI_INSTANCE_ID=$UAZAPI_INSTANCE_ID
ENV UAZAPI_API_TOKEN=$UAZAPI_API_TOKEN
ENV OUTREACH_CRON_SECRET=$OUTREACH_CRON_SECRET
ENV OWNER_PHONE=$OWNER_PHONE
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV ENABLE_LOCAL_AUTH=$ENABLE_LOCAL_AUTH
ENV LOCAL_AUTH_EMAIL=$LOCAL_AUTH_EMAIL
ENV LOCAL_AUTH_PASSWORD=$LOCAL_AUTH_PASSWORD
ENV OUTREACH_DELAY_MS=$OUTREACH_DELAY_MS

# Arquivos pdfkit necessários em runtime
COPY --from=builder /app/node_modules/pdfkit/js/data ./node_modules/pdfkit/js/data

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Pasta de dados persistentes
RUN mkdir -p /app/data

EXPOSE 3000
CMD ["node", "server.js"]
