/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: "standalone",
  images: {
    remotePatterns: [],
  },
  // Injeta variáveis de ambiente do build (build args do EasyPanel) no bundle
  env: {
    SUPABASE_URL: process.env.SUPABASE_URL ?? "",
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY ?? "",
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
    NEXTAUTH_URL: process.env.NEXTAUTH_URL ?? "",
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET ?? "",
    APIFY_TOKEN: process.env.APIFY_TOKEN ?? "",
    APIFY_API_BASE_URL: process.env.APIFY_API_BASE_URL ?? "",
    PROSPECT_APIFY_INSTAGRAM_TASK_ID: process.env.PROSPECT_APIFY_INSTAGRAM_TASK_ID ?? "",
    PROSPECT_APIFY_INSTAGRAM_ACTOR_ID: process.env.PROSPECT_APIFY_INSTAGRAM_ACTOR_ID ?? "",
    PROSPECT_APIFY_LINKEDIN_TASK_ID: process.env.PROSPECT_APIFY_LINKEDIN_TASK_ID ?? "",
    PROSPECT_APIFY_LINKEDIN_ACTOR_ID: process.env.PROSPECT_APIFY_LINKEDIN_ACTOR_ID ?? "",
    PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID: process.env.PROSPECT_APIFY_GOOGLE_MAPS_TASK_ID ?? "",
    PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID: process.env.PROSPECT_APIFY_GOOGLE_MY_BUSINESS_TASK_ID ?? "",
    GEMINI_API_KEY: process.env.GEMINI_API_KEY ?? "",
    GEMINI_API_BASE_URL: process.env.GEMINI_API_BASE_URL ?? "",
    GEMINI_MODEL: process.env.GEMINI_MODEL ?? "",
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY ?? "",
    UAZAPI_API_URL: process.env.UAZAPI_API_URL ?? "",
    UAZAPI_INSTANCE_ID: process.env.UAZAPI_INSTANCE_ID ?? "",
    UAZAPI_API_TOKEN: process.env.UAZAPI_API_TOKEN ?? "",
    OUTREACH_CRON_SECRET: process.env.OUTREACH_CRON_SECRET ?? "",
    OUTREACH_DELAY_MS: process.env.OUTREACH_DELAY_MS ?? "0",
    OUTREACH_MIN_SCORE: process.env.OUTREACH_MIN_SCORE ?? "0",
    OWNER_PHONE: process.env.OWNER_PHONE ?? "",
    ENABLE_LOCAL_AUTH: process.env.ENABLE_LOCAL_AUTH ?? "",
    LOCAL_AUTH_EMAIL: process.env.LOCAL_AUTH_EMAIL ?? "",
    LOCAL_AUTH_PASSWORD: process.env.LOCAL_AUTH_PASSWORD ?? "",
    LOCAL_AUTH_NAME: process.env.LOCAL_AUTH_NAME ?? "",
    LEADS_STORAGE_PROVIDER: process.env.LEADS_STORAGE_PROVIDER ?? "",
    USE_LOCAL_STORAGE: process.env.USE_LOCAL_STORAGE ?? "false",
    PROSPECTING_ENABLE_DEMO_FALLBACK: process.env.PROSPECTING_ENABLE_DEMO_FALLBACK ?? "false",
  },
};

export default nextConfig;
