#!/bin/sh
# Escreve variáveis de ambiente num arquivo .env para o Next.js standalone ler
cat > /app/.env << EOF
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
UAZAPI_API_URL=${UAZAPI_API_URL}
UAZAPI_INSTANCE_ID=${UAZAPI_INSTANCE_ID}
UAZAPI_API_TOKEN=${UAZAPI_API_TOKEN}
OUTREACH_CRON_SECRET=${OUTREACH_CRON_SECRET}
OWNER_PHONE=${OWNER_PHONE}
GEMINI_API_KEY=${GEMINI_API_KEY}
ENABLE_LOCAL_AUTH=${ENABLE_LOCAL_AUTH}
LOCAL_AUTH_EMAIL=${LOCAL_AUTH_EMAIL}
LOCAL_AUTH_PASSWORD=${LOCAL_AUTH_PASSWORD}
OUTREACH_DELAY_MS=${OUTREACH_DELAY_MS}
LEADS_STORAGE_PROVIDER=${LEADS_STORAGE_PROVIDER}
NODE_ENV=production
EOF

exec node server.js
